[package]
name = "aoc-devutils"
version = "0.1.0"
authors = ["Damien Vesper <ldamienvesper@gmail.com>"]
edition = "2021"

[dependencies]
dotenv = { version = "0.15.0" }
reqwest = { version = "0.11.13", features = ["blocking", "json"] }
tokio = { version = "1.22.0", features = ["full"] }
